POST http://localhost:8080/events
content-type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3QzQGV4YW1wbGUuY29tIiwiZXhwIjoxNzA4NzcyMTA1LCJ1c2VySWQiOjN9.cw8O-Xq0k56AoA7D0xUZR6KDOCCoWO012ZRRGTvzuzY

{
  "name": "Test event",
  "description": "Test event!!!",
  "location": "A test location",
  "dateTime": "2025-01-01T15:30:00.000Z"
}